### ISSUE TITLE
Sata Power Connector Link

### ISSUE THREAD

**Issue by carlossless** [ploink/psumon#1]
Hi, Awesome project. I've stumbled across it while looking for a SMD or through-hole SATA Power Connector (with no data). Yes the ones you mentioned are hard to find ;). The link you have on the readme no longer works and 404s. Did you happen to maybe find another source for these rare parts, and if so could you share them again?

Thank you!

**Comment by ploink** [comment]
Hi Karolis,

I have no other source for the connector, but searching Aliexpress.com 
for "sata 15p power connector" I found some, though they have the 3 
contacts for each power rail merged in one pin.
https://www.aliexpress.com/item/10pcs-lot-SATA-connector-power-Interface-SATA-15P-welding-seat-SATA-plastic-shell/32710552274.html

The other option is cutting of the data part from this connector. It is 
a bit of a hack, but I it works very well.
http://www.ebay.com/itm/10-Pcs-7-15-Pin-Right-Angle-SMT-Male-Sata-Connector-For-2-5-Hard-Drive-HDD-/171720426198

Best regards,
Ploink

**Comment by carlossless** [comment]
Yep, after looking again with those exact keywords I found a bunch more. Including these ones: https://www.aliexpress.com/item/10PCS-Hard-disk-interface-SATA-15P-male-connector-socket-insert-plate-90-degrees/32706493159.html?spm=2114.40010408.3.58.vb3OsK
and
https://www.aliexpress.com/item/Original-new-100-SATA-interface-hard-disk-interface-socket-15P-male-180-degree-line-of-single/32738192943.html?spm=2114.01010208.3.158.SwHNzH&ws_ab_test=searchweb0_0,searchweb201602_2_10065_10068_10069_10017_10080_10082_10081_10060_10061_10062_10056_10037_10055_10054_10033_10059_10078_10079_10073_10070_421_420_10052_10053_10050_10051,searchweb201603_7&btsid=5557b6b3-ce7a-444c-99e0-0176f6f2e174

One of them is probably compatible with the footprint you have on this board.

**Comment by ploink** [comment]
Yes the second one looks identical to mine. I have updated the readme, 
thanks.

**Comment by carlossless** [comment]
Thank you! Closing this issue.
